apiVersion: batch/v1
kind: Job
metadata:
  name: job-backoff-limit-per-index-fail-index
spec:
  completions: 8
  parallelism: 2
  completionMode: Indexed
  backoffLimitPerIndex: 1
  podFailurePolicy:
    rules:
    - action: FailIndex
      onExitCodes:
        operator: In
        values: [42]
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: example
        image: python
        command:
        - python3
        - -c
        - |
          import os, sys, time
          id = int(os.environ.get("JOB_COMPLETION_INDEX"))
          if id == 1:
            sys.exit(1)
          elif id == 2:
            sys.exit(42)
          time.sleep(1)
